### PR TITLE
Code cleanup which increases readability

### PR DESCRIPTION
**Pull request by Cyberlane**
I have added some consistency through the code on how variables are declared, making use of safe navigation operators where possible, expressions on a number of the get only properties and some string interpolation on all errors along with anything else that did string formatting.

If you would like me to squash some of the commits, please let me know. I normally play the safe card and do lots of small commits when sending a pull request to somebody I have not worked with previously.

### CODE REVIEW

**Comment by asbjornu** [comment]
@Cyberlane Thanks for this! I'm not sure we're set up for C# 6 in this project yet, but let me investigate and get back to you. I hope we can merge this, but can't promise anything yet. Stay tuned! :smile:

**Comment by Cyberlane** [comment]
@asbjornu no problem at all!

However, I am facing one problem with this library at the moment. Would you prefer I create an issue first to discuss the problem, or just go ahead and send a pull request with how I think it should be solved and go from there?

**Comment by HaavardGrendal** [comment]
@Cyberlane It is great if you send a pull request and explain your problem. I will be happy to look at it.

**Comment by asbjornu** [comment]
@Cyberlane Now that we have implemented test automation on AppVeyor, can you please rebase this PR on current `master` so we can see if any tests fail?

**Pull request closed without merging**
